### ISSUE TITLE
iOS simulator on M1 is arm

### ISSUE THREAD

**Issue by a4z** [benthevining/Oranges#11]
Just reading through some of the files, for fun and inspiration.

iOS simulator on M1 is arm, so the existing one would not work, I guess

Thought I leave that here as a note.

**Comment by benthevining** [comment]
I actually don't have much experience with the iOS simulator -- do you mean that the current iOS toolchain file wouldn't work on M1?

**Comment by a4z** [comment]
it will compile a binary, but not for the architecture the emulator has on the M1, which is arm64

https://github.com/benthevining/Oranges/blob/3abecc80447466ded25eefe51c4d9c923ed1ccbc/toolchains/ios/ios_simulator.cmake#L18

i386 is also obsolete since years

in general, I would not suggest re-invent the wheel, but refer to this: https://github.com/leetal/ios-cmake
or at least, get some inspiration from there

**Comment by benthevining** [comment]
Ah I see. Thank you for that link, I will have to go through that toolchain file!

I've just added a commit that sets the archs for the iOS simulator to `arm64;x86_64`.
